"""crear_tablas_inventario

Revision ID: e85758b64598
Revises: fc7dac707287
Create Date: 2026-10-06 03:08:44.217920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e85758b64598'
down_revision: Union[str, Sequence[str], None] = 'fc7dac707287'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('unit', sa.Enum('G', 'ML', 'PZA', name='unit_type_enum'), nullable=False),
    sa.Column('current_stock', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('min_stock', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('cost_per_unit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('waste_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingredients_name'), 'ingredients', ['name'], unique=True)
    op.create_table('recipes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('recipe_type', sa.Enum('RECETA', 'SUBRECETA', name='recipe_type_enum'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('yield_quantity', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('yield_unit', sa.Enum('G', 'ML', 'PZA', name='unit_type_enum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipes_name'), 'recipes', ['name'], unique=False)
    op.create_table('production_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recipe_id', sa.UUID(), nullable=False),
    sa.Column('quantity_produced', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('unit', sa.Enum('G', 'ML', 'PZA', name='unit_type_enum'), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('produced_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_logs_created_at'), 'production_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_production_logs_recipe_id'), 'production_logs', ['recipe_id'], unique=False)
    op.create_table('recipe_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recipe_id', sa.UUID(), nullable=False),
    sa.Column('ingredient_id', sa.UUID(), nullable=True),
    sa.Column('subrecipe_id', sa.UUID(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('unit', sa.Enum('G', 'ML', 'PZA', name='unit_type_enum'), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subrecipe_id'], ['recipes.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipe_items_ingredient_id'), 'recipe_items', ['ingredient_id'], unique=False)
    op.create_index(op.f('ix_recipe_items_recipe_id'), 'recipe_items', ['recipe_id'], unique=False)
    op.create_index(op.f('ix_recipe_items_subrecipe_id'), 'recipe_items', ['subrecipe_id'], unique=False)
    op.create_table('stock_movements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('movement_type', sa.Enum('ENTRADA_MANUAL', 'SALIDA_VENTA', 'MERMA', 'PRODUCCION_CONSUMO', 'PRODUCCION_ENTRADA', 'AJUSTE_INVENTARIO', name='movement_type_enum'), nullable=False),
    sa.Column('ingredient_id', sa.UUID(), nullable=True),
    sa.Column('subrecipe_id', sa.UUID(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unit', sa.Enum('G', 'ML', 'PZA', name='unit_type_enum'), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['subrecipe_id'], ['recipes.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_movements_created_at'), 'stock_movements', ['created_at'], unique=False)
    op.create_index(op.f('ix_stock_movements_ingredient_id'), 'stock_movements', ['ingredient_id'], unique=False)
    op.create_index(op.f('ix_stock_movements_movement_type'), 'stock_movements', ['movement_type'], unique=False)
    op.create_index(op.f('ix_stock_movements_subrecipe_id'), 'stock_movements', ['subrecipe_id'], unique=False)
    op.create_table('subrecipe_stocks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recipe_id', sa.UUID(), nullable=False),
    sa.Column('current_stock', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('min_stock', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unit', sa.Enum('G', 'ML', 'PZA', name='unit_type_enum'), nullable=False),
    sa.Column('last_production_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recipe_id')
    )
    op.create_table('waste_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('waste_type', sa.Enum('NATURAL', 'VIDA_UTIL', 'ERROR_HUMANO', 'FALTA_CALIDAD', 'RECHAZO_CLIENTE', 'PROCESO', name='waste_type_enum'), nullable=False),
    sa.Column('ingredient_id', sa.UUID(), nullable=True),
    sa.Column('subrecipe_id', sa.UUID(), nullable=True),
    sa.Column('gross_quantity', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('net_quantity', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('waste_quantity', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('waste_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('unit', sa.Enum('G', 'ML', 'PZA', name='unit_type_enum'), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('registered_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['subrecipe_id'], ['recipes.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_waste_logs_created_at'), 'waste_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_waste_logs_ingredient_id'), 'waste_logs', ['ingredient_id'], unique=False)
    op.create_index(op.f('ix_waste_logs_subrecipe_id'), 'waste_logs', ['subrecipe_id'], unique=False)
    op.create_index(op.f('ix_waste_logs_waste_type'), 'waste_logs', ['waste_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_waste_logs_waste_type'), table_name='waste_logs')
    op.drop_index(op.f('ix_waste_logs_subrecipe_id'), table_name='waste_logs')
    op.drop_index(op.f('ix_waste_logs_ingredient_id'), table_name='waste_logs')
    op.drop_index(op.f('ix_waste_logs_created_at'), table_name='waste_logs')
    op.drop_table('waste_logs')
    op.drop_table('subrecipe_stocks')
    op.drop_index(op.f('ix_stock_movements_subrecipe_id'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_movement_type'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_ingredient_id'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_created_at'), table_name='stock_movements')
    op.drop_table('stock_movements')
    op.drop_index(op.f('ix_recipe_items_subrecipe_id'), table_name='recipe_items')
    op.drop_index(op.f('ix_recipe_items_recipe_id'), table_name='recipe_items')
    op.drop_index(op.f('ix_recipe_items_ingredient_id'), table_name='recipe_items')
    op.drop_table('recipe_items')
    op.drop_index(op.f('ix_production_logs_recipe_id'), table_name='production_logs')
    op.drop_index(op.f('ix_production_logs_created_at'), table_name='production_logs')
    op.drop_table('production_logs')
    op.drop_index(op.f('ix_recipes_name'), table_name='recipes')
    op.drop_table('recipes')
    op.drop_index(op.f('ix_ingredients_name'), table_name='ingredients')
    op.drop_table('ingredients')
    # ### end Alembic commands ###
